services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"

  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.2.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.5.2
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"



  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    depends_on:
      - otel-collector
    environment:
      OTEL_SERVICE_NAME: worker
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8081:8081"

  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    depends_on:
      - worker
      - otel-collector
    environment:
      WORKER_BASE_URL: http://worker:8081
      HTTP_TIMEOUT_MS: "2000"
      OTEL_SERVICE_NAME: gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8080:8080"
