receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  health_check:

exporters:
  debug:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - otlp/jaeger

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug

    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
